name: CI

on:
    push:
        branches:
            - main
    pull_request: ~

jobs:
    tests:
        services:
            postgres:
                image: postgres:15
                ports:
                    - 5432
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: testdb
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                    --tmpfs /var/lib/postgres
        runs-on: "ubuntu-22.04"
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                php:
                    - '8.1'

        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP Action
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    extensions: pdo_pgsql, gd

            -   uses: ramsey/composer-install@v2

            -   name: Run PHPStan analysis
                run: composer run-script phpstan

            -   name: Install Ibexa
                run: php bin/console ibexa:install
                env:
                    DATABASE_URL: "pgsql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/testdb?server_version=15"

            -   name: Run PHPUnit
                run: composer run-script test
                env:
                    DATABASE_URL: "pgsql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/testdb?server_version=15"
